map $http_upgrade $connection_upgrade {
    default upgrade;
    "" close;
}

map $http_cf_connecting_ip $libredesk_client_ip {
    default $http_cf_connecting_ip;
    "" $remote_addr;
}

upstream libredesk_app {
    server app:9000;
    keepalive 32;
}

server {
    listen 8080;
    server_name support.olcepks.ca oledu-knowledgebase.taile67ac7.ts.net;
    client_max_body_size 100M;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
        return 204;
    }

    location / {
        proxy_pass http://libredesk_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Client-IP $libredesk_client_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_buffering off;
    }
}
