#!/usr/bin/env bash
set -Eeuo pipefail

if [[ ${EUID} -eq 0 ]]; then
  echo "Run this script as onionlake-admin, not root." >&2
  exit 1
fi

if ! id -nG | tr ' ' '\n' | grep -qx docker; then
  echo "The current login session does not have docker group membership. Log out and back in." >&2
  exit 1
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
deployment_dir="${HOME}/libredesk"

install -d -m 0750 "${deployment_dir}/data/uploads"
install -d -m 0700 "${deployment_dir}/backups"
install -m 0640 "${script_dir}/compose.yaml" "${deployment_dir}/compose.yaml"
install -m 0644 "${script_dir}/config.production.toml" "${deployment_dir}/config.toml"
install -m 0644 "${script_dir}/nginx.conf" "${deployment_dir}/nginx.conf"
install -m 0750 "${script_dir}/backup.sh" "${deployment_dir}/backup.sh"
install -m 0750 "${script_dir}/deploy-image.sh" "${deployment_dir}/deploy-image.sh"

if [[ ! -f "${deployment_dir}/.env" ]]; then
  umask 077
  {
    echo "POSTGRES_USER=libredesk"
    echo "POSTGRES_DB=libredesk"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 32)"
    echo "REDIS_PASSWORD=$(openssl rand -hex 32)"
    echo "LIBREDESK_ENCRYPTION_KEY=$(openssl rand -hex 16)"
    echo "LIBREDESK_SYSTEM_USER_PASSWORD=Ld-$(openssl rand -hex 22)-9A!"
    echo "LIBREDESK_PORT=9000"
    echo "LIBREDESK_TAILSCALE_IP=100.105.41.61"
  } > "${deployment_dir}/.env"
fi
chmod 0600 "${deployment_dir}/.env"

if ! grep -q '^LIBREDESK_TAILSCALE_IP=' "${deployment_dir}/.env"; then
  echo "LIBREDESK_TAILSCALE_IP=100.105.41.61" >> "${deployment_dir}/.env"
fi

set -a
source "${deployment_dir}/.env"
set +a

# Replace credentials generated by the early hex-only bootstrap version.
if [[ ${LIBREDESK_SYSTEM_USER_PASSWORD} =~ ^[0-9a-f]{48}$ ]]; then
  LIBREDESK_SYSTEM_USER_PASSWORD="Ld-$(openssl rand -hex 22)-9A!"
  temporary_env=$(mktemp "${deployment_dir}/.env.XXXXXX")
  awk -F= -v password="${LIBREDESK_SYSTEM_USER_PASSWORD}" '
    BEGIN { OFS = "=" }
    $1 == "LIBREDESK_SYSTEM_USER_PASSWORD" { $2 = password }
    { print }
  ' "${deployment_dir}/.env" > "${temporary_env}"
  chmod 0600 "${temporary_env}"
  mv "${temporary_env}" "${deployment_dir}/.env"
fi

install -d -m 0750 "${HOME}/.config/systemd/user"
install -m 0644 "${script_dir}/libredesk-backup.service" "${HOME}/.config/systemd/user/"
install -m 0644 "${script_dir}/libredesk-backup.timer" "${HOME}/.config/systemd/user/"
systemctl --user daemon-reload
systemctl --user enable --now libredesk-backup.timer

cd "${deployment_dir}"
docker compose config --quiet
docker compose pull
docker compose up -d db redis
docker compose run --rm --no-deps \
  -e LIBREDESK_SYSTEM_USER_PASSWORD="${LIBREDESK_SYSTEM_USER_PASSWORD}" \
  app ./libredesk --install --idempotent-install --yes --config=/libredesk/config.toml
docker compose up -d
